---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 8080, host: 8080}]
  customize:
    cableconnected1: 'on'
provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
suites:
  - name: default
    run_list:
      - recipe[gogs::default]
    attributes:
